// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIKeyUsedFallback() {
  return window['go']['main']['App']['APIKeyUsedFallback']();
}

export function ChangedFiles() {
  return window['go']['main']['App']['ChangedFiles']();
}

export function ExplainFile(arg1) {
  return window['go']['main']['App']['ExplainFile'](arg1);
}

export function FileDiff(arg1) {
  return window['go']['main']['App']['FileDiff'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}
