// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gitdiff} from '../models';
import {diffparse} from '../models';
import {config} from '../models';
import {checks} from '../models';

export function APIKeyUsedFallback():Promise<boolean>;

export function ChangedFiles():Promise<Array<gitdiff.FileChange>>;

export function CommitFileDiff(arg1:string,arg2:string):Promise<diffparse.FileDiff>;

export function CommitFiles(arg1:string):Promise<Array<gitdiff.FileChange>>;

export function ExplainAllChanges():Promise<string>;

export function ExplainAllCommitChanges(arg1:string):Promise<string>;

export function ExplainCommitFile(arg1:string,arg2:string):Promise<string>;

export function ExplainFile(arg1:string):Promise<string>;

export function FileDiff(arg1:string):Promise<diffparse.FileDiff>;

export function GetConfig():Promise<config.Config>;

export function Greet(arg1:string):Promise<string>;

export function HasAPIKey():Promise<boolean>;

export function ListChecks():Promise<Array<checks.Check>>;

export function RecentCommits(arg1:number,arg2:number):Promise<Array<gitdiff.Commit>>;

export function RunCheckAll(arg1:string):Promise<string>;

export function RunCheckOnAllCommitFiles(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetAPIKey(arg1:string):Promise<void>;
